name: 'Pull Request Validator'
description: 'Verify that the pull request and configuration were successfully created.'
author: 'moseoh'
inputs:
  token:
    description: 'GitHub token to authenticate requests.'
    required: true
  pull-request-title-regex:
    description: 'Regular expression to validate the pull request title.'
    required: false
  branch-name-regex:
    description: 'Regular expression to validate the branch name.'
    required: false
  commit-message-regex:
    description: 'Regular expression to validate the commit messages.'
    required: false
runs:
  using: 'node20'
  main: 'lib/index.js'
branding:
  icon: 'git-pull-request'
  color: 'blue'