name: Pull Request Validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited

permissions:
  contents: read
  pull-requests: read
  issues: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Request Validator
        uses: azqazq195/actions.pull-request-validator@action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-title-regex: "^(feat|refactor|bug|hotfix):.*$"
          branch-name-regex: "^(feat|refactor|bug|hotfix)-.*$"
          commit-message-regex: "^(feat|refactor|fix|chore|remove|rename|test):.*$"

