name: Pull Request Validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Request Validator
        uses: azqazq195/actions.pull-request-validator@action
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

