name: Pull Request Validator

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Validator
        uses: azqazq195/actions.pull-request-validator@master
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

